version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5000"  # Хост:5001 → Контейнер:5000
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/app
    restart: unless-stopped